### ISSUE TITLE
Still tokens out of LOS visible

### ISSUE THREAD

**Issue by R0TEAM** [caewok/fvtt-token-visibility#4]
Actual Foundry (stable) - and perfectvision, about face, Levels.

**Comment by caewok** [comment]
I am going to need more if there is an issue here. What settings are you using for Token Visibility? Do you have a scene JSON you can upload here?

**Comment by R0TEAM** [comment]
<img width="1920" alt="hc_001" src="https://user-images.githubusercontent.com/29609164/200212355-bfcc459f-c727-49fa-9ab6-bd74d1d6f663.png">
<img width="1920" alt="hc_002" src="https://user-images.githubusercontent.com/29609164/200212383-6845a516-370d-422e-8ecf-74fb893ab169.png">

**Comment by caewok** [comment]
Possibly fixed in v0.3.0. Feel free to re-open an issue if this persists.

**Comment by R0TEAM** [comment]
still the same problem with 0.30 ...
(the "Wall hight dont work properly ..." issue looks fixed)

**Comment by caewok** [comment]
I cannot replicate this. Does it happen with just libWrapper, Wall Height, and Alternative Token Visibility modules active? If no, does it happen with just libWrapper, Wall Height, Alternative Token Visibility, and Perfect Vision modules active?

**Comment by R0TEAM** [comment]
Have maked a couple of Testing ....
It looks AlternateToken Visibility dont care over restrictions from other vision limiting settings ...
Have 3 pictures ...
The first with 360° View of the Token and Perfect Vision not enabled (aka - no sight radius limit)
here all is right and nice ...
The scond with an view angle restriction (as you can see on the shadow) - but ATV dont care and show the same tokens as before ..
And the third with PerfectVision enabled - thats doing additional an sight radius limit .... but ATV show still the same tokens as from the start ...
<img width="936" alt="hc_001" src="https://user-images.githubusercontent.com/29609164/202920592-20da75ff-2c88-4de1-b062-66fc9e423aea.png">
<img width="938" alt="hc_002" src="https://user-images.githubusercontent.com/29609164/202920598-dd245f4b-88e9-4bb0-9199-3ccc2f9e8fca.png">
<img width="931" alt="hc_003" src="https://user-images.githubusercontent.com/29609164/202920604-58ad38c0-4e1c-40d2-82a0-25fdbf8209c1.png">

**Comment by R0TEAM** [comment]
Oh - and to answer your questions ....
without PerfectVision the problem is only partialy gone - as the tokens who should not visible from the view arc arestill visible - so no - perfect vision doing not realy here an difference
Have the same problem with only AlternateTokenVisibilty + Levels + libwrapper + wallhight

**Comment by caewok** [comment]
It was the limited angle vision that was throwing it off. Fixed in v0.3.2. Thanks!

**Comment by R0TEAM** [comment]
sorry to say (wrote) this ...
but the problem is still here ... the angle vision limitation now work .... (thanks)
but the sight radius limitation is still ignored and all token visible as without sight radius limit ....

**Comment by caewok** [comment]
Thanks for the clarification. I will open a separate issue regarding the sight radius limitation. I would have thought Perfect Vision was using the range detection for this, which Alt Token Visibility leaves to PV if available. But apparently not!

**Comment by caewok** [comment]
@R0TEAM What are your settings for the scene in Perfect Vision?

**Comment by R0TEAM** [comment]
<img width="928" alt="hc_001" src="https://user-images.githubusercontent.com/29609164/203584297-9f73f416-3f88-4df4-b246-bbf0a600c0cb.png">

**Comment by R0TEAM** [comment]
o.k. - it "looks" it is basical now working ....
The update from you (ATV) dont fix it finaly (but get an new bug, but this later ...) , but with the new PerfectVision update, ATV dont show now any unexpected token anmore .... Thanks ...
but to the new bug - the canvas freeze and i get this :
`libWrapper-wrapper.js:669 Uncaught TypeError: constrainedTokenBorder.toPolygon is not a function
[Detected 4 packages: tokenvisibility, lib-wrapper, perfect-vision, levels]
    at Area3d._targetWithinLimitedAngleVision (Area3d.js:387:42)
    at Area3d.percentAreaVisible (Area3d.js:404:16)
    at Area3d.hasLOS (Area3d.js:154:33)
    at testLOSArea3d (visibility_los.js:247:17)
    at DetectionModeBasicSight._testLOSDetectionMode (visibility_los.js:139:16)
    at 🎁DetectionMode.prototype._testLOS#0 (libWrapper-wrapper.js:187:52)
    at 🎁DetectionModeBasicSight.prototype._testPoint#perfect-vision (detection-mode.js:146:23)
    at 🎁DetectionModeBasicSight.prototype._testPoint#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:40711:36
    at Array.some (<anonymous>)
    at DetectionModeBasicSight.testVisibility (foundry.js:40711:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at DetectionModeBasicSight.testVisibilityDetectionMode (visibility_range.js:64:10)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁DetectionModeBasicSight.prototype.testVisibility#perfect-vision (detection-mode.js:126:28)
    at 🎁DetectionModeBasicSight.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at CanvasVisibility.testVisibility (foundry.js:33435:39)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at CanvasVisibility.testVisibilityCanvasVisibility (visibility_range.js:47:10)
    at CanvasVisibility.visibilityWrapper (wrappers.js:103:25)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at get isVisible [as isVisible] (foundry.js:45582:38)
    at CanvasVisibility.restrictVisibility (foundry.js:33358:68)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CanvasVisibility.prototype.restrictVisibility#perfect-vision (visibility.js:46:20)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CanvasVisibility.prototype.restrictVisibility#0 (libWrapper-wrapper.js:189:20)
    at 🎁CanvasVisibility.prototype.refresh#perfect-vision (visibility.js:391:18)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁CanvasVisibility.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at #update (foundry.js:41473:58)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)
_targetWithinLimitedAngleVision @ Area3d.js:387
percentAreaVisible @ Area3d.js:404
hasLOS @ Area3d.js:154
testLOSArea3d @ visibility_los.js:247
_testLOSDetectionMode @ visibility_los.js:139
🎁DetectionMode.prototype._testLOS#0 @ libWrapper-wrapper.js:187
🎁DetectionModeBasicSight.prototype._testPoint#perfect-vision @ detection-mode.js:146
🎁DetectionModeBasicSight.prototype._testPoint#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:40711
testVisibility @ foundry.js:40711
🎁call_wrapped @ libWrapper-wrapper.js:507
testVisibilityDetectionMode @ visibility_range.js:64
🎁DetectionMode.prototype.testVisibility#0 @ libWrapper-wrapper.js:187
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁DetectionModeBasicSight.prototype.testVisibility#perfect-vision @ detection-mode.js:126
🎁DetectionModeBasicSight.prototype.testVisibility#0 @ libWrapper-wrapper.js:187
testVisibility @ foundry.js:33435
🎁call_wrapped @ libWrapper-wrapper.js:507
testVisibilityCanvasVisibility @ visibility_range.js:47
visibilityWrapper @ wrappers.js:103
🎁CanvasVisibility.prototype.testVisibility#0 @ libWrapper-wrapper.js:187
get isVisible @ foundry.js:45582
restrictVisibility @ foundry.js:33358
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁CanvasVisibility.prototype.restrictVisibility#perfect-vision @ visibility.js:46
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁CanvasVisibility.prototype.restrictVisibility#0 @ libWrapper-wrapper.js:189
🎁CanvasVisibility.prototype.refresh#perfect-vision @ visibility.js:391
🎁call_wrapper @ libWrapper-wrapper.js:591
🎁CanvasVisibility.prototype.refresh#0 @ libWrapper-wrapper.js:189
#update @ foundry.js:41473
t.emit @ ticker.min.mjs:8
e.update @ ticker.min.mjs:8
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
Show 4 more frames`

**Comment by caewok** [comment]
Closing as fixed; Thanks for adding a new issue for the last comment.
